### PR TITLE
Adding preserve_empty_lines option

### PR DESCRIPTION
**Pull request by jncasey**
Adding the feature I requested in #95. 

Not stripping out the empty lines was causing problems with the festival backend and preserve_punctuation, so I took the approach of stripping out the empty lines pre-phonemization and then reinserting them afterward.

I want to flag that I changed the conversion of the input text to a list from a generator to list comprehension [here](https://github.com/jncasey/phonemizer/blob/a8a33d7557550ef63912e38b010c3fb6900f1dcc/phonemizer/phonemize.py#L261) since I needed to run through the list a second time to preserve the empty lines, and I thought this made the code easier to read than making another generator. I'm assuming that this won't make a big difference on performance given how I think phonemizer is generally used.

### CODE REVIEW

**Comment by jncasey** [comment]
This is going to need some more work. 

I guess all of my testing was with njobs=1. With parallel jobs, it seems the flattener doesn't the empty lines (at least with espeak). I'll look into fixing it.

**Comment by jncasey** [comment]
It turns out this was an existing bug in the library. With njobs>1 and an empty input (or one that gets preprocessed to empty), `_flatten` in the espeak backend would throw an IndexError.

Even if you decide not to merge this new feature, it might still be a good idea to add this fix (or equivalent)

**Comment by hadware** [comment]
Alright, this is _almost_ ready for merge. Could you try and add a test or two in order to make codecov happy again, and then we're go :)

PS: don't forget to pull, i've merged the master onto your branch to fix some conflicts.

**Comment by jncasey** [comment]
Okay, great! I'll have a look at this soon.

**Comment by jncasey** [comment]
These extra tests should hit those missed lines.

[Sorry, I don't have access to the festival backend on my local computer at the moment, but I can't imagine any reason why they wouldn't pass.]

**Comment by hadware** [comment]
Alright, we're go!

I'll merge that and (if I have the right permissions) upload it to pipy tomorrow! Great work, thanks for that @jncasey !

**Pull request merged**
