### PR TITLE
Add ignore option to disable language_switch by default

### PR DESCRIPTION
**Pull request by ZihanJin**

### CODE REVIEW

**Comment by mmmaat** [comment]
Hi ZihanJin,

Thanks for the PR! I have few comments/questions.
* First a simple bug: https://travis-ci.org/bootphon/phonemizer/builds/621088061#L484
* You are saying there are many language detection mistakes, can you have examples? Is the `(.+?)` regular expression not generic enough?
* Your new `ignore` option is almost identical to `keep-flags`, right? In that case I would prefer to replace the actual `keep-flags` by your `ignore` one, so as to keep the interface as simple as possible. What do you think?

**Comment by ZihanJin** [comment]
Oops sorry I was testing how to ignore language switch I thought I
modified it in my own repo!

I didn't look into espeak-ng source code, but it frequently misrecognizes
Italian/French with English words when I have a code-switching sentence. So
I was trying to just skip this function.

**Comment by mmmaat** [comment]
indeed this language switching is related to espeak-ng, not phonemizer! Phonemizer just deals with the language tags: (fr), (en), etc...

**Comment by ZihanJin** [comment]
Got it! Sorry for the following stupid question: so does it mean when
phonemizer didn't have this option, espeak-ng still translates
code-switching sentences automatically anyway? Meaning there is no way to
skip that unless I make changes in espeak-ng...

Thank you Mathieu!

**Comment by mmmaat** [comment]
yes exactly!

**Pull request closed without merging**
