### PR TITLE
[WIP] fixes to --preserve-punctuation 

### LINKED ISSUE #108: Maximum recursion depth exceeded with --preserve-punctuation and long documents
**Describe the bug**
If you try to phonemize a long document (say, a Project Gutenberg ebook) and preserve punctuation, phonemize throws
`fatal error: maximum recursion depth exceeded in comparison`

**Phonemizer version**
phonemizer-3.0.1
available backends: espeak-1.48.3, segments-2.2.0
uninstalled backends: espeak-mbrola, festival

**System**
Both macOS 11.6 and Ubuntu 20.10

**To reproduce**
`phonemize --preserve-punctuation pg67147.txt`
where pg67147.txt is [this ebook](https://www.gutenberg.org/ebooks/67147), or anything relatively long.

**Expected behavior**
This looks like a result of the Punctuation restore methods being recursive and my (probably unreasonably long) use case. 

**Additional context**
I'm happy to try refactoring the `restore` methods into a single iterative method. Just let me know if you'd like me to contribute.

### PR DESCRIPTION
**Pull request by jncasey**
This reworks a few things related to preserving punctuation.

- Fixes the inconsistency described in #106. Now word separators appear in the same locations whether `preserve_punctuation` is True or False.
- Addresses part of the problem described in #104 (but doesn't return the output to what it was in 0.3, which I believe was incorrect – they'd also need to use a non-None word separator, maybe, to get what they're after?)
- Fixes #108 by refactoring the restore method to be iterative instead of recursive

A number of the tests had to be updated due to that first bullet point.

### CODE REVIEW

**Comment by jncasey** [comment]
@hadware I think this is good to go, but it definitely changes the output when preserving punctuation compared to previous versions of phonemizer. This way seems much more consistent to me – the output will have the same number of word separators whether punctuation is being preserved or not. 

See the tests I modified for examples of the new output.

**Comment by hadware** [comment]
Alright, super cool.

I'll review the PR probably tomorrow, and hopefully we can merge this. This is fantastic, thanks again for your work!

**Comment by jncasey** [comment]
Great! Let me know if you need me to make any changes. 

And thank you for this project. It's replaced my DIY solution of a transformers model trained on the CMUDict, and is so much faster and more accurate.

**Comment by hadware** [comment]
This is looking good! I'm merging this. I'd like to add a test with the large e-book from #108 , then i'll release a new version (Probably `3.2.1` since this contains some pretty major changes)

**Comment by jncasey** [comment]
Great! This also closed #106, and makes PR #112 redundant

**Comment by hadware** [comment]
Oh, btw. Since you seem to have a very good understanding of the whole lib, would you mind if I ask for your opinion on future PR's (from other github users)? I'm also making you "triager" for this repo.

**Comment by jncasey** [comment]
Happy to help as much as I can!

**Pull request merged**
