### PR TITLE
Punctuation fixes

### LINKED ISSUE #108: Maximum recursion depth exceeded with --preserve-punctuation and long documents
**Describe the bug**
If you try to phonemize a long document (say, a Project Gutenberg ebook) and preserve punctuation, phonemize throws
`fatal error: maximum recursion depth exceeded in comparison`

**Phonemizer version**
phonemizer-3.0.1
available backends: espeak-1.48.3, segments-2.2.0
uninstalled backends: espeak-mbrola, festival

**System**
Both macOS 11.6 and Ubuntu 20.10

**To reproduce**
`phonemize --preserve-punctuation pg67147.txt`
where pg67147.txt is [this ebook](https://www.gutenberg.org/ebooks/67147), or anything relatively long.

**Expected behavior**
This looks like a result of the Punctuation restore methods being recursive and my (probably unreasonably long) use case. 

**Additional context**
I'm happy to try refactoring the `restore` methods into a single iterative method. Just let me know if you'd like me to contribute.

### PR DESCRIPTION
**Pull request by agonzalezd**
This branch fixes #108, recursion errors aligning long texts

### CODE REVIEW

**Comment by agonzalezd** [comment]
I am having some issues while transcribing a specific file... The output is not the same if I run it more than once. The last three sentences sometimes get compromised, and sometimes they return a segmentation fault.

This is the content of the file in question:

```
Guerre en Ukraine : de l’offensive ratée au carnage, un mois de guerre de l’armée russe.
Les fronts sont figés, quatre semaines après l’invasion lancée par Moscou le vingt-quatre février.
Revers tactiques et pauses volontaires des troupes s’entremêlent et l’hypothèse d’un échec militaire devient envisageable.
La machine offensive s’est bloquée.
Lancée le vingt-quatre février, la fulgurante guerre d’annihilation de l’Ukraine voulue par Vladimir Poutine connaît depuis trois semaines un ralentissement brutal.
Un enlisement réel, masqué par l’orage de feu projeté sur les civils, dans les hôpitaux de Tchernihiv, les banlieues résidentielles de Kiev, le théâtre de Marioupol.
Il est trop tôt pour solder les comptes d’une opération d’invasion qui, en plus de la Crimée et des régions séparatistes du Donbass prises en deux-mille-quatorze, a déjà conquis quarante-neuf-mille kilomètres carrés supplémentaires de territoire ukrainien, autant que le Danemark.
Mais, après un mois de guerre, revers tactiques et pauses volontaires des troupes s’entremêlent, pour dessiner un échec possible de l’armée russe.
Quand François Hollande a jailli de sa voiture, après quatre heures trente de route, il avait un sourire grand comme ça et des fourmis plein les jambes.
Plus de dix ans qu’il n’avait pas prononcé de discours lors d’une campagne présidentielle.
Mardi vingt-deux mars, Anne Hidalgo, la candidate socialiste, donnait un meeting à Limoges, et elle avait invité le dernier président socialiste en date à venir la soutenir.
Un moment qui aurait dû être tout à fait banal, à trois semaines du premier tour, pour essayer une ultime fois de réanimer une campagne à l’agonie.
Les talibans ont ordonné, mercredi vingt-trois mars, la fermeture des collèges et lycées pour les filles en Afghanistan, quelques heures seulement après leur réouverture, a confirmé un responsable taliban.
La prévention s’impose donc à tout citoyen mais aussi à la collectivité, car cette pandémie a démontré la fragilité des systèmes de soins.
En plus de la lutte contre l’alcool et le tabac, la prévention s’appuie sur une meilleure alimentation et une vie plus active et moins sédentaire.
Bien que non satisfaisantes, les prévalences de l’alcoolisme et du tabagisme baissent en France, alors que l’inactivité physique et la sédentarité des Français s’installent.
Près de quarante-deux pour cent des adultes jeunes entre dix-huit et quarante-quatre ans sont sédentaires, c’est-à-dire assis plus de huit heures par jour, avec soixante-dix-neuf pour cent de ce temps passés devant un écran de loisir.
Que deviendront les commandes chinoises, qui représentent un quart des ventes mondiales du dernier-né des sept-cent-trente-sept, estimées à cinq cents appareils cette année?
Qu’en sera-t-il de la conduite de l’enquête sur l’accident?
Qui conseillerait aujourd’hui à un jeune étudiant en droit d’abandonner ses études pour suivre la stratégie d’ascension sociale suggérée par Vautrin?
qu’est-ce qui nous pousse à voter?
Voterait-on dans la seule optique de maintenir la continuité des institutions politiques?
```

For example:

```
ki kɔ̃sɛjʁɛt oʒuʁdyi iksy a œ̃ ʒøn etydjɑ̃ ɑ̃ dʁwa dabɑ̃dɔne sez etyd puʁ syivʁ la stʁateʒi dasɑ̃sjɔ̃ sosjal syɡʒeʁe paʁ votʁɛ̃ 
kɛs ki nu pus a vote 
votʁɛtɔ̃ dɑ̃ la sœl ɔptik də mɛ̃tniʁ la kɔ̃tinyite dez ɛ̃stitysjɔ̃ politik 
```
that "iksy" is not in the original text

Or with a "4++" (katʁ plysplys) after aujourd’hui (oʒuʁdyi): 

```
ki kɔ̃sɛjʁɛt oʒuʁdyi katʁ plysplys a œ̃ ʒøn etydjɑ̃ ɑ̃ dʁwa dabɑ̃dɔne sez etyd puʁ syivʁ la stʁateʒi dasɑ̃sjɔ̃ sosjal syɡʒeʁe paʁ votʁɛ̃ 
```

Or even weirder outputs:

```
ki ktl#tl#sɒjʀɒt oʒuʀdʌi ʒeve(kl) ɛ a ɜə ʒən etʌdiy yə dʀwa dabydəne səə etʌdə puʀ səivʀ lə stʀateʒi dasysitl# sosial sʌɡʒeʀe paʀ votʀœ 
kɒəs ki nuə pus a vote 
votʀɒətl#ə dyə lə stsl əptik də mœtniʀ lə ktl#tinəite dəə œstitʌsitl#ə politikə
```

```
ki kɔ̃sɛjʁɛt oʒuʁdyi aʁobazld() y ə əə əəə əəəəəə əə əəəə dəəəəəəə əəə əəəəə əəə əəəəə əə əəəəəəəə dəəəəəə əəəəəə əəəəəəə əəə əəəəə?
kəəə əə əəə əəə ə əəəə?
əəəəəəəəə əəə əə əəə əəəəə əə əəəəəəə əə əəəəəəəəə əəə əəəəəəəəəə əəəəəəəə?
```

Maybe a memory leak or something related to the modified code? I don't know if any of this rings any bell...

**Comment by jncasey** [comment]
Hi, I made this branch to solve a problem I was having on a particular project (as I described in #108). But I haven't tested it extensively, and I've only used it on English text. 

That said, I don't seem to be having the problem you're describing on my local machine using this branch.

```
phonemize --preserve-punctuation -l fr-fr --language-switch remove-flags phonemizing_test.txt 
```
returns a consistent output, and the last three lines are always
```
ki kɔ̃sɛjʁɛt oʒuʁdyi a œ̃ ʒøn etydjɑ̃ ɑ̃ dʁwa dabɑ̃dɔne sez etyd puʁ syivʁ la stʁateʒi dasɑ̃sjɔ̃ sosjal syɡʒeʁe paʁ votʁɛ̃? 
kɛs ki nu pus a vote? 
votʁɛtɔ̃ dɑ̃ la sœl ɔptik də mɛ̃tniʁ la kɔ̃tinyite dez ɛ̃stitysjɔ̃ politik? 
```
...which matches up with what little French I remember from high school and college.

**Comment by agonzalezd** [comment]
Probably due to different versions? I am currently using the following espeak-ng version:

```
eSpeak NG text-to-speech: 1.49.2  Data at: /usr/lib/x86_64-linux-gnu/espeak-ng-data
```

A new version 1.50 seems to be available but I couldn't install it with apt-get. 

The texts in English I tried didn't throw any error at all. I haven't checked it in more other languages either. 

I am also interested on using phonemizer for long texts, or at least a big quantity of them, which seems a bit complicated as you have experienced. But if I am having inconsistencies and wrong transcriptions, I cannot use this tool. This is why I am trying to revive your branch here :)

Thanks by the way for your quick response

**Comment by jncasey** [comment]
I ran the recent test on macOS laptop, where I had to compile espeak-ng from source, so my version here is 
```
eSpeak NG text-to-speech: 1.51-dev  Data at: /usr/local/share/espeak-ng-data
```

I haven't noticed any issues on my Ubuntu workstation, which has espeak-ng installed via apt. But, like I said, I've mainly been working with English text.

**Comment by hadware** [comment]
Oh, sorry for not being a bit more attentive, I haven't been maintaining this package properly for now (I'm the new maintainer btw, @mmmaat game me the keys to his _opus magnus_). 

I'll look into your other PR ASAP, do what needs to be done to merge it, and once that's done, go back to this one. I think that's what you would have expected me to do, right?

**Comment by jncasey** [comment]
No worries at all! I'm just grateful that this library exists in the first place. I'm no real developer, just a hobbyist with some free time for a personal project.

And yeah, if you want to review the first PR, that'd be great. Once it's good to go, I'm happy to try implementing the other changes in my local branch in a more organized way. Or even to discuss with you if my suggested changes are wanted in the first place.

**Comment by agonzalezd** [comment]
Perfect! Thanks!

**Pull request closed without merging**
